# Generated by Django 4.2 on 2024-08-23 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_item_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
    ]
