# Generated by Django 4.2 on 2024-08-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_article_author_article_like_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='n_hit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
